global:
  scrape_interval: 15s
  evaluation_interval: 30s

scrape_configs:
  - job_name: face-blur-model-service
    honor_labels: True
    static_configs:
      - targets:
          - 'api.privfacy.net:3000'
